version: 2

gomod:
  proxy: false

builds:
  - main: ./cmd/snip
    binary: snip
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

homebrew_casks:
  - repository:
      owner: edouard-claude
      name: homebrew-tap
    homepage: "https://github.com/edouard-claude/snip"
    description: "CLI proxy that reduces LLM token consumption by 60-90% by filtering shell output"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
