name: "go-test"
version: 1
description: "Condensed go test output with pass/fail summary"

match:
  command: "go"
  subcommand: "test"
  exclude_flags: ["-json", "-v", "-bench", "-run"]

inject:
  args: ["-json"]
  skip_if_present: ["-json", "-v", "-bench"]

pipeline:
  - action: "keep_lines"
    pattern: "\\S"
  - action: "keep_lines"
    pattern: "\"Action\":\"(pass|fail|skip|output)\""
  - action: "remove_lines"
    pattern: "\"Output\":\"=== RUN"
  - action: "ndjson_stream"
    group_by: "Package"
    format: "{{.Key}}: {{.Count}} events"
  - action: "format_template"
    template: "{{.count}} packages:\n{{.lines}}"

on_error: "passthrough"
